# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robinhood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robinhooduser',
            name='token',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
