# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robinhood', '0002_robinhooduser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robinhooduser',
            name='token',
            field=models.BinaryField(max_length=500),
        ),
    ]
