# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robinhood', '0004_auto_20171003_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='robinhooduser',
            name='signedin',
            field=models.BooleanField(default=False),
        ),
    ]
